on:
  push:
    branches:
      - main
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        with:
          release-type: maven
          package-name: ems
          bump-minor-pre-major: true
